### ISSUE TITLE
Add four social media icon

### ISSUE THREAD

**Issue by AyushSarode** [AyushSarode/Social-media-buttons.github.io#1]

**Comment by Abhishek3223** [comment]
hey can i worj on this ? please assignthis to me

**Comment by abhijeetanand29** [comment]
Can you assign this issue to me?

**Comment by AyushSarode** [comment]
Sure go ahead!

**Comment by AyushSarode** [comment]
You give star to this repo!

**Comment by roshan2152** [comment]
Hey  @AyushSarode  can I work on this?

**Comment by AyushSarode** [comment]
> Hey @AyushSarode can I work on this?

Two participants are already assigned @roshan2152 .
Checkout other Issues
