### ISSUE TITLE
Align text and buttons at center of the page

### ISSUE THREAD

**Issue by AyushSarode** [AyushSarode/Social-media-buttons.github.io#15]

**Comment by Divyanshusir** [comment]
please assign it to me

**Comment by Erum640** [comment]
please assign me this issue

**Comment by Sourz-101** [comment]
hey , i want to work on this , assign this to me

**Comment by Erum640** [comment]
Hey please assign this to me.

**Comment by Manujdixit** [comment]
@AyushSarode , I would like to work on this. Please assign it to me.

**Comment by AyushSarode** [comment]
> hey , i want to work on this , assign this to me

You Wanted to do that issue but I couldn't give you that so yup...

**Comment by AyushSarode** [comment]
And for everyone imma create new issue so stay tune. Give a star to this repo
