### ISSUE TITLE
Change the color of hover effect

### ISSUE THREAD

**Issue by AyushSarode** [AyushSarode/Social-media-buttons.github.io#20]
![Screenshot 2022-10-08 013509](https://user-images.githubusercontent.com/72145248/194644423-f3e4b9ba-bbd8-4bab-952f-ec787dfaf9b0.png)

**Comment by kiran-thilak** [comment]
can i work on this issue?

**Comment by AyushSarode** [comment]
Sure. Go ahead!

**Comment by kiran-thilak** [comment]
Could you please explain the expected result.

**Comment by AyushSarode** [comment]
> Could you please explain the expected result.

It should match the bg color, that's it!

**Comment by AyushSarode** [comment]
> > Could you please explain the expected result.
> 
> It should match the bg color, that's it!

Please check it out webpage, I just changed bg color to white

**Comment by AyushSarode** [comment]
If you want to add some color matching things you can free to do

**Comment by kiran-thilak** [comment]
Changed the color to white itself
![image](https://user-images.githubusercontent.com/8852764/194653791-51d14d90-da53-4fde-844d-4065def6386b.png)

**Comment by sukalyanbisui** [comment]
can you assign this.
