### ISSUE TITLE
Make the text and buttons big in mobile

### ISSUE THREAD

**Issue by AyushSarode** [AyushSarode/Social-media-buttons.github.io#21]
I saw this on my mobile and all the elements were small, make it big but not so big 
![WhatsApp Image 2022-10-08 at 1 56 19 AM](https://user-images.githubusercontent.com/72145248/194647407-f9c6a721-ceaa-4cdf-8399-a0564fcc9d3d.jpeg)

**Comment by Vipdhruvkalra** [comment]
Please assign this issue to me I'll do it

**Comment by AyushSarode** [comment]
Sure, Go ahead!

**Comment by DHRUVKHANDELWAL00** [comment]
HEY @AyushSarode , can i be assigned too. I can definitely try to do it

**Comment by AyushSarode** [comment]
> HEY @AyushSarode , can i be assigned too. I can definitely try to do it

Sure, go ahead!

**Comment by DHRUVKHANDELWAL00** [comment]
HEY @AyushSarode i have done the necessary changes and made PR. if u need some other changes please let me know. and if it is correct please accept it under hacktoberfest .

**Comment by madmaxWMFU** [comment]
Hi! Can you assign it to me?

**Comment by AyushSarode** [comment]
Sure
