### ISSUE TITLE
Change the color of hover effect

### ISSUE THREAD

**Issue by AyushSarode** [AyushSarode/Social-media-buttons.github.io#25]

**Comment by madmaxWMFU** [comment]
Hi! Can you assign it to me?

**Comment by AyushSarode** [comment]
> Hi! Can you assign it to me?

Can you work on #21 ?

**Comment by Maryam-Momoh** [comment]
hello can i work on this?

**Comment by AyushSarode** [comment]
> hello can i work on this?

Sure, color must be matchable to the UI

**Comment by Maryam-Momoh** [comment]
> > hello can i work on this?
> 
> Sure, color must be matchable to the UI

okay, no problem

**Comment by madmaxWMFU** [comment]
> #21

Yes, I can.

**Comment by Maryam-Momoh** [comment]
is a gradient color okay or a solid color?

**Comment by AyushSarode** [comment]
> is a gradient color okay or a solid color?

Try gradient!

**Comment by inbuilt-aura** [comment]
Is this issue open,if yes i would love to try out a few of them cuz my expertise in in css.

**Comment by AyushSarode** [comment]
> Is this issue open,if yes i would love to try out a few of them cuz my expertise in in css.

Sorry @inbuilt-aura , @Maryam-Momoh  is already working on it.

**Comment by inbuilt-aura** [comment]
@AyushSarode I would love to try glass effect, can two persons work on this issue but with different code? Since, I am new to hacktoberfest, I don't know.

**Comment by Maryam-Momoh** [comment]
> Try gradient!


https://user-images.githubusercontent.com/75956011/195672418-d9632772-3865-4bb9-9bfc-28f75888cf13.mp4

is this okay?

**Comment by Maryam-Momoh** [comment]
https://user-images.githubusercontent.com/75956011/195704935-ab9adbe6-9f39-45d6-b6c4-99b7a4acf7f3.mp4

this is how it looks

**Comment by AyushSarode** [comment]
> 
> https://user-images.githubusercontent.com/75956011/195704935-ab9adbe6-9f39-45d6-b6c4-99b7a4acf7f3.mp4
> 
> this is how it looks. 
Go for PR
