### ISSUE TITLE
Add Code of conduct.md

### ISSUE THREAD

**Issue by AyushSarode** [AyushSarode/Social-media-buttons.github.io#8]

**Comment by Mohit-Aasirwal** [comment]
Hey I can do this very well. Kindly assign me for this task.

**Comment by AyushSarode** [comment]
Sure! Go ahead.

**Comment by AyushSarode** [comment]
> Sure! Go ahead.

**Comment by AyushSarode** [comment]
> Sure! Go ahead.

Kindly give star to this repo.

**Comment by BharatChotwani** [comment]
Hi Ayush , kindly assign to me.

**Comment by AyushSarode** [comment]
> Hi Ayush , kindly assign to me.

Go ahead!
